-- Natal chart admin store for Postgres (Neon or any Postgres 13+). Idempotent: safe to run again.
-- Run once (Neon SQL Editor or `psql "$DATABASE_URL_UNPOOLED" -f db/schema.sql`) before the first deploy;
-- the app never migrates Postgres at request time.
-- Mirrors SQLite migrations 1-3 in natal/store.py (SCHEMA_VERSION = 3).
-- The server connects as the database owner via DATABASE_URL; the public Data API roles get no access.

CREATE TABLE IF NOT EXISTS submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TEXT NOT NULL,
    visitor_id TEXT,
    display_name TEXT,
    raw_input TEXT NOT NULL,
    status TEXT NOT NULL,
    error_code TEXT,
    summary TEXT,
    place TEXT,
    sun_sign TEXT,
    moon_sign TEXT,
    asc_sign TEXT,
    fingerprint TEXT,
    consent INTEGER NOT NULL DEFAULT 0 CHECK (consent IN (0, 1)),
    utm_source TEXT, utm_medium TEXT, utm_campaign TEXT, utm_content TEXT, utm_term TEXT,
    short_code TEXT
);
CREATE INDEX IF NOT EXISTS submissions_created_at ON submissions(created_at);
CREATE INDEX IF NOT EXISTS submissions_visitor ON submissions(visitor_id, created_at);
CREATE INDEX IF NOT EXISTS submissions_status ON submissions(status);
CREATE INDEX IF NOT EXISTS submissions_short_code ON submissions(short_code);

CREATE TABLE IF NOT EXISTS utm_channels (
    key TEXT PRIMARY KEY CHECK (length(key) BETWEEN 1 AND 64),
    label_ko TEXT NOT NULL,
    utm_source TEXT NOT NULL,
    utm_medium TEXT NOT NULL,
    note TEXT,
    is_active INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
    sort_order INTEGER NOT NULL DEFAULT 100,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS utm_campaigns (
    key TEXT PRIMARY KEY CHECK (length(key) BETWEEN 1 AND 64),
    label_ko TEXT NOT NULL,
    note TEXT,
    starts_on TEXT,
    ends_on TEXT,
    is_active INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS utm_links (
    code TEXT PRIMARY KEY CHECK (length(code) = 6),
    target_path TEXT NOT NULL CHECK (
        substr(target_path, 1, 1) = '/' AND substr(target_path, 1, 2) <> '//'
        AND strpos(target_path, E'\\') = 0 AND strpos(target_path, ':') = 0 AND length(target_path) <= 200),
    channel_key TEXT REFERENCES utm_channels(key),
    campaign_key TEXT REFERENCES utm_campaigns(key),
    utm_source TEXT NOT NULL,
    utm_medium TEXT NOT NULL,
    utm_campaign TEXT NOT NULL,
    utm_content TEXT,
    memo TEXT,
    created_by TEXT,
    archived_at TEXT,
    created_at TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS utm_links_active_combo
    ON utm_links(target_path, utm_source, utm_medium, utm_campaign, COALESCE(utm_content, ''))
    WHERE archived_at IS NULL;

CREATE TABLE IF NOT EXISTS utm_clicks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL,
    clicked_at TEXT NOT NULL,
    counted INTEGER NOT NULL CHECK (counted IN (0, 1)),
    exclude_note TEXT CHECK (exclude_note IN ('head', 'preview-bot')),
    ua_family TEXT
);
CREATE INDEX IF NOT EXISTS utm_clicks_code ON utm_clicks(code, clicked_at);
CREATE INDEX IF NOT EXISTS utm_clicks_at ON utm_clicks(clicked_at);

CREATE TABLE IF NOT EXISTS login_attempts (
    key_hash TEXT NOT NULL,
    attempted_at DOUBLE PRECISION NOT NULL
);
CREATE INDEX IF NOT EXISTS login_attempts_key ON login_attempts(key_hash, attempted_at);

CREATE TABLE IF NOT EXISTS shares (
    token TEXT PRIMARY KEY,
    kind TEXT NOT NULL,
    title TEXT,
    payload TEXT NOT NULL,
    delete_hash TEXT NOT NULL,
    created_at TEXT NOT NULL
);

-- Default channels (only when the table is empty, like SQLite migration 2).
INSERT INTO utm_channels (key, label_ko, utm_source, utm_medium, sort_order, created_at)
SELECT v.key, v.label_ko, v.utm_source, v.utm_medium, v.sort_order,
       to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')
FROM (VALUES
    ('instagram', '인스타그램', 'instagram', 'social', 10),
    ('threads', '스레드', 'threads', 'social', 20),
    ('kakao', '카카오톡', 'kakao', 'messenger', 30),
    ('naver_blog', '네이버 블로그', 'naver_blog', 'blog', 40),
    ('youtube', '유튜브', 'youtube', 'video', 50),
    ('x', 'X(트위터)', 'x', 'social', 60),
    ('email', '이메일', 'newsletter', 'email', 70),
    ('offline_qr', '오프라인 QR', 'offline', 'qr', 80)
) AS v(key, label_ko, utm_source, utm_medium, sort_order)
WHERE NOT EXISTS (SELECT 1 FROM utm_channels);

-- Defence in depth: RLS with no policies denies any non-owner role (e.g. a Data API role);
-- the owner connection used by the server bypasses RLS. The anon/authenticated revokes only run
-- where those roles exist (some hosted-Postgres setups); on Neon / plain Postgres they are skipped.
ALTER TABLE submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE utm_channels ENABLE ROW LEVEL SECURITY;
ALTER TABLE utm_campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE utm_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE utm_clicks ENABLE ROW LEVEL SECURITY;
ALTER TABLE login_attempts ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE role_name TEXT;
BEGIN
    FOREACH role_name IN ARRAY ARRAY['anon', 'authenticated'] LOOP
        IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = role_name) THEN
            EXECUTE format('REVOKE ALL ON submissions, utm_channels, utm_campaigns, utm_links, utm_clicks, login_attempts FROM %I', role_name);
            EXECUTE format('REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM %I', role_name);
        END IF;
    END LOOP;
END $$;
